### PR TITLE
Add support for processing the "retry" command.

### PR DESCRIPTION
**Pull request by alevinval**
_Warning: force pushing, making the PR to see travis failures I cannot reproduce._

Supporting the "retry" command and implementing reconnections is the missing development towards having a compliant server sent events client.

### CODE REVIEW

**Review by dolmen — CHANGES_REQUESTED** [review]
This commit has various unrelated changes in multiple files. This will not help to properly merge my own code.

**Comment by alevinval** [comment]
Don't worry then, I will keep it on hold until your refactor comes.

**Comment by alevinval** [comment]
Hi @dolmen.

This branch has now the hardest pending:
- Decoder needs a way to update the `eventSource.retry` attribute when it parses a `retry` event.

I'd welcome any suggestion you may have towards achieving this.

I am in doubts because I don't want to update the interfaces, for something that should be internal to the implementation. At the same time, I don't want to use reflection.

What I would do is:
- The implementation keeps a static map: `map[decoder]eventSource`
- The eventSource implementation is responsible of updating it whenever a new decoder is made.
- The decoder finds a `retry` event, finds itself in the map and updates the corresponding eventSource instance retry value.

Do you like it?

**Comment by dolmen** [comment]
I still haven't had time to review this. Sorry. I still plan to do it.

**Pull request merged**
